apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-cluster
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports: 
    - port: 8558
      name: akka-management
    - port: 8082
      name: akka-remote
  selector:
    app: account-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: account-cluster
  labels:
    app: account-cluster
    cluster: akkabank
spec:
  serviceName: account-service
  replicas: 3
  selector:
    matchLabels:
      app: account-cluster
  template:
    metadata:
      labels:
        app: account-cluster
        cluster: akkabank
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: account-cluster
        image: account:latest
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 10
        ports:
          - containerPort: 8558
            protocol: TCP
            name: akka-management
          - containerPort: 8082
            protocol: TCP
            name: akka-remote
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AkkaRemoting__Host
          value: "$(POD_NAME).account-service"
        - name: MockThirdPartyBank__Port
          value: "5007"
        - name: EmailServiceUri
          value: "https://api.useplunk.com/v1/"
        - name: DomesticTransferRouter__MaxInstancesPerNode
          value: "10"
        envFrom:
        - configMapRef:
            name: bank-env
      initContainers:
      - name: init-account-cluster
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z pg-postgresql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 5432; do echo "Waiting for postgres..."; sleep 3; done;']
