apiVersion: v1
kind: Service
metadata:
  # NOTE: 
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
  #  nginx.ingress.kubernetes.io/affinity: "cookie"
  name: web-cluster-http
  labels:
    app: web-cluster
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - nodePort: 30000
    protocol: TCP
    port: 3000
    targetPort: 80
  selector:
    app: web-cluster
