apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-cluster
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 8558
      name: akka-management
    - port: 8082
      name: akka-remote
    - port: 80
      name: http
  selector:
    app: web-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-cluster
  labels:
    app: web-cluster
    cluster: akkabank
spec:
  serviceName: web-service
  replicas: 1
  selector:
    matchLabels:
      app: web-cluster
  template:
    metadata:
      labels:
        app: web-cluster
        cluster: akkabank
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: web-cluster
        image: web:latest
        imagePullPolicy: Never
        readinessProbe:
          tcpSocket:
            port: http
        livenessProbe:
          tcpSocket:
            port: 9999
          initialDelaySeconds: 10
        ports:
          - containerPort: 8558
            protocol: TCP
            name: akka-management
          - containerPort: 8082
            protocol: TCP
            name: akka-remote
          - containerPort: 80
            protocol: TCP
            name: http
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AkkaRemoting__Host
          value: "$(POD_NAME).web-service"
        - name: DOTNET_URLS
          value: "http://+:80"
        envFrom:
        - configMapRef:
            name: bank-env
      initContainers:
      - name: wait-for-seed-nodes-in-cluster-formation
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv account-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local 9998; do echo waiting for account cluster formation; sleep 3; done"]
